=== afirmaRepository/afirma-mdef-api/src/main/resources/config.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="AfirmaConfig" type="AfirmaConfigType" />
	<!-- ********** SFLY CONFIG ***************************************** -->
	<xsd:complexType name="AfirmaConfigType">
		<xsd:sequence>
			<xsd:element name="PdfAttributes" type="PdfAttributesType" />
			<xsd:element name="Appearance" type="AppearanceType"
				minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>
	<!-- *********** ENUMERATIONS TYPES ***************************************** -->
	<xsd:simpleType name="imageEncodingType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="base64" />
			<xsd:enumeration value="uri" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="SignatureInfoID">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Subject" />
			<xsd:enumeration value="Issuer" />
			<xsd:enumeration value="SerialNumber" />
			<xsd:enumeration value="Reason" />
			<xsd:enumeration value="Location" />
			<xsd:enumeration value="ContactInfo" />
			<xsd:enumeration value="Date" />
		</xsd:restriction>
	</xsd:simpleType>
	<!-- ******* PDF ATTRIBUTES DEFINITION ***************************************** -->
	<xsd:complexType name="PdfAttributesType">
		<xsd:sequence>
			<xsd:element name="signaturePosition" type="xsd:positiveInteger"
				minOccurs="0" />
			<xsd:element name="params" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="location" type="xsd:string"
							minOccurs="0" />
						<xsd:element name="reason" type="xsd:string"
							minOccurs="0" />
						<xsd:element name="contactInfo" type="xsd:string"
							minOccurs="0" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<!-- ******** APPEARANCE DEFINITION ***************************************** -->
	<xsd:complexType name="AppearanceType">
		<xsd:sequence>
			<xsd:element name="Rect" type="RectType" minOccurs="0" />
			<!--<xsd:element name="Background" type="BackgroundType" minOccurs="0"/> -->
			<xsd:element name="Foreground" type="ForegroundType"
				minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>
	<!-- RECT DEFINITION -->
	<xsd:complexType name="RectType">
		<xsd:attribute name="x0" type="xsd:positiveInteger" use="required" />
		<xsd:attribute name="y0" type="xsd:positiveInteger" use="required" />
		<xsd:attribute name="x1" type="xsd:positiveInteger" use="required" />
		<xsd:attribute name="y1" type="xsd:positiveInteger" use="required" />
	</xsd:complexType>
	<!-- FOREGROUND DEFINITION -->
	<xsd:complexType name="ForegroundType">
		<xsd:sequence>
			<xsd:element name="image" type="ImageType" minOccurs="0" />
			<xsd:element name="text" type="TextType" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>
	<!-- IMAGE DEFINITION -->
	<xsd:complexType name="ImageType">
		<xsd:sequence>
			<xsd:element name="data" type="xsd:string" />
			<xsd:element name="imageSize" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="width" type="xsd:positiveInteger"
						use="required" />
					<xsd:attribute name="height" type="xsd:positiveInteger"
						use="required" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="position" type="PositionType"
				minOccurs="0" />
		</xsd:sequence>
		<xsd:attribute name="encodeType" type="imageEncodingType"
			use="required" />
	</xsd:complexType>
	<!-- TEXT DEFINITION -->
	<xsd:complexType name="TextType">
		<xsd:sequence>
			<xsd:element name="properties" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="color" type="xsd:string" use="required" />
					<xsd:attribute name="fontSize" type="xsd:positiveInteger"
						use="required" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="position" type="PositionType"
				minOccurs="0" />
			<xsd:element name="SignatureInfos" type="SignatureInfosType"
				minOccurs="0" />
			<xsd:element name="ArbitraryText" type="ArbitraryTextType"
				minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>
	<!-- SignatureInfos DEFINITION -->
	<xsd:complexType name="SignatureInfosType">
		<xsd:sequence>
			<xsd:element name="signatureInfo" minOccurs="0"
				maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="title" type="xsd:string" use="required" />
					<xsd:attribute name="id" type="SignatureInfoID" use="required" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<!-- ArbitraryText DEFINITION -->
	<xsd:complexType name="ArbitraryTextType">
		<xsd:sequence>
			<xsd:element name="textItem" type="TextItemType"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<!-- TextItemType DEFINITION -->
	<xsd:complexType name="TextItemType">
		<xsd:sequence>
			<xsd:element name="font" type="FontType" minOccurs="0" />
			<xsd:element name="position" type="PositionType" />
			<xsd:element name="text" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>
	<!-- FontType DEFINITION -->
	<xsd:complexType name="FontType">
		<xsd:attribute name="fontSize" type="xsd:positiveInteger"
			use="required" />
	</xsd:complexType>
	<!-- POSITION DEFINITION -->
	<xsd:complexType name="PositionType">
		<xsd:attribute name="x" type="xsd:nonNegativeInteger"
			use="required" />
		<xsd:attribute name="y" type="xsd:nonNegativeInteger"
			use="required" />
	</xsd:complexType>
</xsd:schema>

=== afirmaRepository/afirma-mdef-api/src/test/resources/configPrueba2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<AfirmaConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="config.xsd">
	<PdfAttributes>
<!--		<signatureAlg>SHA1</signatureAlg>
 		<validationMethod>PPKMS</validationMethod>   -->
		<signaturePosition>2</signaturePosition>
		<params>
			<location>Madrid</location>
			<reason>Soy el autor del documento</reason>
			<contactInfo>+34 555 666 777</contactInfo>
		</params>
	</PdfAttributes>
	<Appearance>
		<Rect x0="100" y0="50" x1="500" y1="250" />
<!-- 		<Background>
			<image encodeType="uri">
				<data>src\test\resources\SignatureLogo.png</data>
				<imageSize width="400" height="200" />
				<position x="0" y="0" />
			</image>
		</Background>
 -->		<Foreground>
			<image encodeType="uri">
				<!-- <data>c:\temp\foreground.jpg</data> -->
				<data>src\test\resources\logoEjercito.png</data>
				<!-- <imageSize width="150" height="200" /> -->
				<imageSize width="400" height="200" />
				<position x="0" y="0" />
			</image>
			<text>
				<!--<properties color="0 0 0" fontSize="8" />
				 <position x="170" y="20" /> -->
				<properties color="0 0 0" fontSize="12"/>
				<position x="100" y="50" />
				<SignatureInfos>
					<signatureInfo title="Autor de la firma: " id="Subject" />
					<signatureInfo title="Emisor del certificado: " id="Issuer" />
					<signatureInfo title="Número de serie: " id="SerialNumber" />
					<signatureInfo title="Razón: " id="Reason" />
					<signatureInfo title="Localización: " id="Location" />
					<signatureInfo title="Información de contacto: " id="ContactInfo" />
					<signatureInfo title="Fecha de firma: " id="Date" />
				</SignatureInfos>
				<ArbitraryText>
					<textItem>
						<font fontSize="8" />
						<position x="170" y="100" />
						<text>Texto arbitrario 1</text>
					</textItem>
					<textItem>
						<font fontSize="8" />
						<position x="170" y="80" />
						<text>Texto arbitrario 2</text>
					</textItem>
				</ArbitraryText>
			</text>
		</Foreground>
	</Appearance>
</AfirmaConfig>
